# Site settings
title: friedcheese.org
email: d-torrance@monmouthcollege.edu
description: > # this means to ignore newlines until "baseurl:"
  Frying cheese since 1999.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://friedcheese.org" # the base hostname & protocol for your site
twitter_username: profzoom81
github_username:  d-torrance

# Build settings
markdown: kramdown
